import { CountryCodeDict } from "./types";

export default {
    "US": { "code": "1", "lengths": [10], "name": "United States"},
    "CA": { "code": "1", "lengths": [10], "name": "Canada"},
    "RU": { "code": "7", "lengths": [10], "name": "Russia"},
    "KZ": { "code": "7", "lengths": [10], "name": "Kazakhstan"},
    "EG": { "code": "20", "lengths": [9], "name": "Egypt"},
    "ZA": { "code": "27", "lengths": [9], "name": "South Africa"},
    "GR": { "code": "30", "lengths": [10], "name": "Greece"},
    "NL": { "code": "31", "lengths": [9], "name": "Netherlands"},
    "BE": { "code": "32", "lengths": [9], "name": "Belgium"},
    "FR": { "code": "33", "lengths": [9], "name": "France"},
    "ES": { "code": "34", "lengths": [9], "name": "Spain"},
    "HU": { "code": "36", "lengths": [8, 9], "name": "Hungary"},
    "IT": { "code": "39", "lengths": [9, 10], "name": "Italy"},
    "RO": { "code": "40", "lengths": [9], "name": "Romania"},
    "CH": { "code": "41", "lengths": [9], "name": "Switzerland"},
    "AT": { "code": "43", "lengths": [10, 11, 12, 13], "name": "Austria"},
    "GB": { "code": "44", "lengths": [10], "name": "United Kingdom"},
    "DK": { "code": "45", "lengths": [8], "name": "Denmark"},
    "SE": { "code": "46", "lengths": [9], "name": "Sweden"},
    "NO": { "code": "47", "lengths": [8], "name": "Norway"},
    "PL": { "code": "48", "lengths": [9], "name": "Poland"},
    "DE": { "code": "49", "lengths": [10, 11], "name": "Germany"},
    "PE": { "code": "51", "lengths": [9], "name": "Peru"},
    "MX": { "code": "52", "lengths": [10], "name": "Mexico"},
    "CU": { "code": "53", "lengths": [8], "name": "Cuba"},
    "AR": { "code": "54", "lengths": [10], "name": "Argentina"},
    "BR": { "code": "55", "lengths": [10, 11], "name": "Brazil"},
    "CL": { "code": "56", "lengths": [9], "name": "Chile"},
    "CO": { "code": "57", "lengths": [10], "name": "Colombia"},
    "VE": { "code": "58", "lengths": [10], "name": "Venezuela"},
    "MY": { "code": "60", "lengths": [9, 10], "name": "Malaysia"},
    "AU": { "code": "61", "lengths": [9], "name": "Australia"},
    "ID": { "code": "62", "lengths": [10, 11, 12], "name": "Indonesia"},
    "PH": { "code": "63", "lengths": [10], "name": "Philippines"},
    "NZ": { "code": "64", "lengths": [9], "name": "New Zealand"},
    "SG": { "code": "65", "lengths": [8], "name": "Singapore"},
    "TH": { "code": "66", "lengths": [9], "name": "Thailand"},
    "JP": { "code": "81", "lengths": [10], "name": "Japan"},
    "KR": { "code": "82", "lengths": [9, 10], "name": "South Korea"},
    "VN": { "code": "84", "lengths": [9, 10], "name": "Vietnam"},
    "CN": { "code": "86", "lengths": [11], "name": "China"},
    "TR": { "code": "90", "lengths": [10], "name": "Turkey"},
    "IN": { "code": "91", "lengths": [10], "name": "India"},
    "PK": { "code": "92", "lengths": [10], "name": "Pakistan"},
    "AF": { "code": "93", "lengths": [9], "name": "Afghanistan"},
    "LK": { "code": "94", "lengths": [9], "name": "Sri Lanka"},
    "MM": { "code": "95", "lengths": [8, 9], "name": "Myanmar"},
    "IR": { "code": "98", "lengths": [10], "name": "Iran"},
    "MA": { "code": "212", "lengths": [9], "name": "Morocco"},
    "DZ": { "code": "213", "lengths": [9], "name": "Algeria"},
    "TN": { "code": "216", "lengths": [8], "name": "Tunisia"},
    "LY": { "code": "218", "lengths": [9], "name": "Libya"},
    "GM": { "code": "220", "lengths": [7], "name": "Gambia"},
    "SN": { "code": "221", "lengths": [9], "name": "Senegal"},
    "MR": { "code": "222", "lengths": [8], "name": "Mauritania"},
    "ML": { "code": "223", "lengths": [8], "name": "Mali"},
    "GN": { "code": "224", "lengths": [8], "name": "Guinea"},
    "CI": { "code": "225", "lengths": [8], "name": "Ivory Coast"},
    "BF": { "code": "226", "lengths": [8], "name": "Burkina Faso"},
    "NE": { "code": "227", "lengths": [8], "name": "Niger"},
    "TG": { "code": "228", "lengths": [8], "name": "Togo"},
    "BJ": { "code": "229", "lengths": [8], "name": "Benin"},
    "MU": { "code": "230", "lengths": [7], "name": "Mauritius"},
    "LR": { "code": "231", "lengths": [7, 8], "name": "Liberia"},
    "SL": { "code": "232", "lengths": [8], "name": "Sierra Leone"},
    "GH": { "code": "233", "lengths": [9], "name": "Ghana"},
    "NG": { "code": "234", "lengths": [10], "name": "Nigeria"},
    "TD": { "code": "235", "lengths": [8], "name": "Chad"},
    "CF": { "code": "236", "lengths": [8], "name": "Central African Republic"},
    "CM": { "code": "237", "lengths": [8], "name": "Cameroon"},
    "CV": { "code": "238", "lengths": [7], "name": "Cape Verde"},
    "ST": { "code": "239", "lengths": [7], "name": "Sao Tome and Principe"},
    "GQ": { "code": "240", "lengths": [9], "name": "Equatorial Guinea"},
    "GA": { "code": "241", "lengths": [8], "name": "Gabon"},
    "CG": { "code": "242", "lengths": [9], "name": "Congo (Brazzaville)"},
    "CD": { "code": "243", "lengths": [9], "name": "Congo (Kinshasa)"},
    "AO": { "code": "244", "lengths": [9], "name": "Angola"},
    "GW": { "code": "245", "lengths": [7], "name": "Guinea-Bissau"},
    "IO": { "code": "246", "lengths": [7], "name": "British Indian Ocean Territory"},
    "SC": { "code": "248", "lengths": [6], "name": "Seychelles"},
    "SD": { "code": "249", "lengths": [9], "name": "Sudan"},
    "RW": { "code": "250", "lengths": [9], "name": "Rwanda"},
    "ET": { "code": "251", "lengths": [9], "name": "Ethiopia"},
    "SO": { "code": "252", "lengths": [8], "name": "Somalia"},
    "DJ": { "code": "253", "lengths": [8], "name": "Djibouti"},
    "KE": { "code": "254", "lengths": [9], "name": "Kenya"},
    "TZ": { "code": "255", "lengths": [9], "name": "Tanzania"},
    "UG": { "code": "256", "lengths": [9], "name": "Uganda"},
    "BI": { "code": "257", "lengths": [8], "name": "Burundi"},
    "MZ": { "code": "258", "lengths": [9], "name": "Mozambique"},
    "ZM": { "code": "260", "lengths": [9], "name": "Zambia"},
    "MG": { "code": "261", "lengths": [9, 10], "name": "Madagascar"},
    "RE": { "code": "262", "lengths": [9], "name": "Reunion"},
    "ZW": { "code": "263", "lengths": [9], "name": "Zimbabwe"},
    "NA": { "code": "264", "lengths": [9], "name": "Namibia"},
    "MW": { "code": "265", "lengths": [9], "name": "Malawi"},
    "LS": { "code": "266", "lengths": [8], "name": "Lesotho"},
    "BW": { "code": "267", "lengths": [7], "name": "Botswana"},
    "SZ": { "code": "268", "lengths": [7, 8], "name": "Swaziland"},
    "KM": { "code": "269", "lengths": [7], "name": "Comoros"},
    "ER": { "code": "291", "lengths": [7], "name": "Eritrea"},
    "AW": { "code": "297", "lengths": [7], "name": "Aruba"},
    "FO": { "code": "298", "lengths": [6], "name": "Faroe Islands"},
    "GI": { "code": "350", "lengths": [8], "name": "Gibraltar"},
    "PT": { "code": "351", "lengths": [9], "name": "Portugal"},
    "LU": { "code": "352", "lengths": [8, 9], "name": "Luxembourg"},
    "IE": { "code": "353", "lengths": [9], "name": "Ireland"},
    "IS": { "code": "354", "lengths": [7, 9], "name": "Iceland"},
    "AL": { "code": "355", "lengths": [9], "name": "Albania"},
    "MT": { "code": "356", "lengths": [8], "name": "Malta"},
    "CY": { "code": "357", "lengths": [8], "name": "Cyprus"},
    "FI": { "code": "358", "lengths": [9, 10], "name": "Finland"},
    "BG": { "code": "359", "lengths": [9], "name": "Bulgaria"},
    "LT": { "code": "370", "lengths": [8], "name": "Lithuania"},
    "LV": { "code": "371", "lengths": [8], "name": "Latvia"},
    "EE": { "code": "372", "lengths": [7, 8], "name": "Estonia"},
    "MD": { "code": "373", "lengths": [8], "name": "Moldova"},
    "AM": { "code": "374", "lengths": [8], "name": "Armenia"},
    "BY": { "code": "375", "lengths": [9], "name": "Belarus"},
    "AD": { "code": "376", "lengths": [6], "name": "Andorra"},
    "MC": { "code": "377", "lengths": [8, 9], "name": "Monaco"},
    "SM": { "code": "378", "lengths": [6, 10], "name": "San Marino"},
    "VA": { "code": "379", "lengths": [11], "name": "Vatican City State"},
    "UA": { "code": "380", "lengths": [9], "name": "Ukraine"},
    "RS": { "code": "381", "lengths": [9], "name": "Serbia"},
    "ME": { "code": "382", "lengths": [8], "name": "Montenegro"},
    "HR": { "code": "385", "lengths": [8, 9], "name": "Croatia"},
    "SI": { "code": "386", "lengths": [8], "name": "Slovenia"},
    "BA": { "code": "387", "lengths": [8], "name": "Bosnia and Herzegovina"},
    "MK": { "code": "389", "lengths": [8], "name": "North Macedonia"},
    "CZ": { "code": "420", "lengths": [9], "name": "Czech Republic"},
    "SK": { "code": "421", "lengths": [9], "name": "Slovakia"},
    "LI": { "code": "423", "lengths": [7], "name": "Liechtenstein"},
    "BZ": { "code": "501", "lengths": [7], "name": "Belize"},
    "GT": { "code": "502", "lengths": [8], "name": "Guatemala"},
    "SV": { "code": "503", "lengths": [8], "name": "El Salvador"},
    "HN": { "code": "504", "lengths": [8], "name": "Honduras"},
    "NI": { "code": "505", "lengths": [8], "name": "Nicaragua"},
    "CR": { "code": "506", "lengths": [8], "name": "Costa Rica"},
    "PA": { "code": "507", "lengths": [7, 8], "name": "Panama"},
    "PM": { "code": "508", "lengths": [6], "name": "Saint Pierre and Miquelon"},
    "HT": { "code": "509", "lengths": [8], "name": "Haiti"},
    "GP": { "code": "590", "lengths": [9], "name": "Guadeloupe"},
    "BO": { "code": "591", "lengths": [8], "name": "Bolivia"},
    "GY": { "code": "592", "lengths": [7], "name": "Guyana"},
    "EC": { "code": "593", "lengths": [9], "name": "Ecuador"},
    "GF": { "code": "594", "lengths": [9], "name": "French Guiana"},
    "PY": { "code": "595", "lengths": [9], "name": "Paraguay"},
    "MQ": { "code": "596", "lengths": [9], "name": "Martinique"},
    "SR": { "code": "597", "lengths": [7], "name": "Suriname"},
    "UY": { "code": "598", "lengths": [8], "name": "Uruguay"},
    "CW": { "code": "599", "lengths": [7], "name": "Curacao"},
    "TL": { "code": "670", "lengths": [7, 8], "name": "East Timor"},
    "AQ": { "code": "672", "lengths": [6], "name": "Australian External Territories"},
    "BN": { "code": "673", "lengths": [7], "name": "Brunei Darussalam"},
    "NR": { "code": "674", "lengths": [7], "name": "Nauru"},
    "PG": { "code": "675", "lengths": [7, 8], "name": "Papua New Guinea"},
    "TO": { "code": "676", "lengths": [7], "name": "Tonga"},
    "SB": { "code": "677", "lengths": [7], "name": "Solomon Islands"},
    "VU": { "code": "678", "lengths": [7], "name": "Vanuatu"},
    "FJ": { "code": "679", "lengths": [7], "name": "Fiji"},
    "PW": { "code": "680", "lengths": [7], "name": "Palau"},
    "WF": { "code": "681", "lengths": [6], "name": "Wallis and Futuna"},
    "YT": { "code": "262", "lengths": [9], "name": "Mayotte"},
    "MF": { "code": "590", "lengths": [9], "name": "Saint Martin"},
    "BL": { "code": "590", "lengths": [9], "name": "Saint Barthelemy"},
    "TF": { "code": "262", "lengths": [9], "name": "French Southern Territories"},
    "PF": { "code": "689", "lengths": [6], "name": "French Polynesia"},
    "NC": { "code": "687", "lengths": [6], "name": "New Caledonia"},
    "SJ": { "code": "47", "lengths": [8], "name": "Svalbard and Jan Mayen"},
    "BV": { "code": "47", "lengths": [8], "name": "Bouvet Island"},
    "VG": { "code": "1", "lengths": [10], "name": "Virgin Islands, British"},
    "KY": { "code": "1", "lengths": [10], "name": "Cayman Islands"},
    "BM": { "code": "1", "lengths": [10], "name": "Bermuda"},
    "AI": { "code": "1", "lengths": [10], "name": "Anguilla"},
    "TC": { "code": "1", "lengths": [10], "name": "Turks and Caicos Islands"},
    "MS": { "code": "1", "lengths": [10], "name": "Montserrat"},
    "GU": { "code": "1", "lengths": [10], "name": "Guam"},
    "AS": { "code": "1", "lengths": [10], "name": "American Samoa"},
    "MP": { "code": "1", "lengths": [10], "name": "Northern Mariana Islands"},
    "VI": { "code": "1", "lengths": [10], "name": "Virgin Islands, U.S."},
    "PR": { "code": "1", "lengths": [10], "name": "Puerto Rico"},
    "UM": { "code": "1", "lengths": [10], "name": "United States Minor Outlying Islands"},
    "MH": { "code": "692", "lengths": [7], "name": "Marshall Islands"}
} as CountryCodeDict